/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m11.view;

/**
 *
 * @author JoseLuis.Canivano
 */
public class AppMainJFrameJPanelNorth extends javax.swing.JPanel {
    private String mHeaderLabel ;
    /**
     * Creates new form AppMainJFrameJPanelNorth
     */
    public AppMainJFrameJPanelNorth(String pHeaderLabel)
    { mHeaderLabel = pHeaderLabel;

      initComponents();
      initComponentsMan();
        
    }

    
    private void initComponentsMan()
    { jtfHeaderLabel.setText(mHeaderLabel);
        
    }
    
    protected void setLabelText(String pStr)
    { mHeaderLabel = pStr;
      jtfHeaderLabel.setText(mHeaderLabel);        
      jtfHeaderLabel.setColumns(pStr.length());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jtfHeaderLabel = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        jtfHeaderLabel.setEditable(false);
        jtfHeaderLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfHeaderLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfHeaderLabel.setToolTipText("");
        jtfHeaderLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        add(jtfHeaderLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jtfHeaderLabel;
    // End of variables declaration//GEN-END:variables
}
