/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m11.view;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author JoseLuis.Canivano
 */
public class AppMainJFrameJPanelWest extends javax.swing.JPanel {
    AppMainJFrame     mAppMainJFrame;
    String[] mMenuOperaciones = null;
    
    public AppMainJFrameJPanelWest(AppMainJFrame pParent, String[] menuOperaciones ) 
    { mAppMainJFrame = pParent;
      mMenuOperaciones = menuOperaciones;
      
      initComponents();
      
      initComponentsMan();
    }    
    
    /**
     * Creates new form AppMainJFrameJPanelWest
     */
    public AppMainJFrameJPanelWest() {
        initComponents();
    }

    private void initComponentsMan()
    {
      DefaultTreeModel dtm = (DefaultTreeModel) jTreeMenu.getModel();
      DefaultMutableTreeNode dmtRoot = (DefaultMutableTreeNode) dtm.getRoot();
      dmtRoot.removeAllChildren();
      dmtRoot.setUserObject(mMenuOperaciones[0]);
      for(int dIdx=1;dIdx<mMenuOperaciones.length;dIdx++)  
      { // dtm.insertNodeInto(new DefaultMutableTreeNode(szOp), dmtRoot, dmtRoot.getChildCount());
        dmtRoot.add(new DefaultMutableTreeNode(mMenuOperaciones[dIdx]));
      }
      dtm.reload(dmtRoot);      
      
      
      jTreeMenu.addMouseListener(new MouseAdapter() 
      { @Override
        public void mouseClicked(MouseEvent me) 
        { processClickOnJTree(me);
        }
      });
    }
    
    //
    private void processClickOnJTree(MouseEvent me)
    { String opcion = "";
            
      TreePath tp = jTreeMenu.getPathForLocation(me.getX(), me.getY());
      if (tp != null) opcion = tp.toString();
      if((opcion!=null)&&(me.getClickCount()==2))
      { mAppMainJFrame.procesaOperacion(opcion);
      }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeMenu = new javax.swing.JTree();

        jScrollPane1.setViewportView(jTreeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTreeMenu;
    // End of variables declaration//GEN-END:variables
}
